const TASK_LIST = [
  {
    title: "Cracking The Code Interview",
    expectedTimeHrs: 100,
    isCrucial: false,
    needFocus: false,
    deadline: new Date("2023-06-30").getTime(),
  },
  {
    title: "Calculus IV Exam",
    expectedTimeHrs: 10,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-07-25").getTime(),
  },
  {
    title: "Phenomenal Transport",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-07-30").getTime(),
  },
  {
    title: "Numerical Calculus",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-07-30").getTime(),
  },
  {
    title: "DIO Bootcamp",
    expectedTimeHrs: 25,
    isCrucial: true,
    needFocus: false,
    deadline: new Date("2022-07-28").getTime(),
  },
  {
    title: "Pomotask",
    expectedTimeHrs: 20,
    isCrucial: true,
    needFocus: false,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "AWS Developer Course",
    expectedTimeHrs: 15,
    isCrucial: false,
    needFocus: false,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "Calculus Book",
    expectedTimeHrs: 150,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2023-07-19").getTime(),
  },
  {
    title: "Physics Book",
    expectedTimeHrs: 150,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2023-07-19").getTime(),
  },
  {
    title: "Microservices Course",
    expectedTimeHrs: 10,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "Linear Algebra",
    expectedTimeHrs: 25,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "Algorithms",
    expectedTimeHrs: 60,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-12-30").getTime(),
  },
  {
    title: "Differential Equations",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "KhanAcademy Computer Science",
    expectedTimeHrs: 25,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "Elasticsearch",
    expectedTimeHrs: 10,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "RabbitMQ",
    expectedTimeHrs: 5,
    isCrucial: false,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "AWS Udemy Course",
    expectedTimeHrs: 40,
    isCrucial: false,
    needFocus: false,
    deadline: new Date("2022-12-30").getTime(),
  },
  {
    title: "Differentiation Rules",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "Applications of Differentiation",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "Applications of Integration",
    expectedTimeHrs: 5,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-08-30").getTime(),
  },
  {
    title: "Techniques of Integration",
    expectedTimeHrs: 8,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "Further Applications of Integration",
    expectedTimeHrs: 5,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "Differential Equations",
    expectedTimeHrs: 10,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "Parametric Equations and Polar Coordinates",
    expectedTimeHrs: 8,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-09-30").getTime(),
  },
  {
    title: "Sequences, Series, and Power Series",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "Vectors and the Geometry of Space",
    expectedTimeHrs: 8,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "Vector Functions",
    expectedTimeHrs: 5,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "Partial Derivatives",
    expectedTimeHrs: 10,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-10-30").getTime(),
  },
  {
    title: "Multiple Integrals",
    expectedTimeHrs: 15,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-11-30").getTime(),
  },
  {
    title: "Vector Calculus",
    expectedTimeHrs: 10,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-11-30").getTime(),
  },
  {
    title: "Physics Khan Academy",
    expectedTimeHrs: 50,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-12-30").getTime(),
  },
  {
    title: "ADM",
    expectedTimeHrs: 6,
    isCrucial: true,
    needFocus: true,
    deadline: new Date("2022-07-25").getTime(),
  },
] as any[];

TASK_LIST.forEach((item, idx) => {
  item.id = idx + 1;
  item.createdAt = Date.now();
  item.workedTimeMin = 0;
  item.successful = false;
});

export { TASK_LIST };
