import TaskModel from "../model/TaskModel";

export const TASK_LIST = [
  {
    id: 1,
    title: "Jogar Vôlei",
    priorityLevel: 1,
    healthLevel: 2,
    expectedTimeHours: 120,
    needFocus: false,
    deadline: new Date(Date.now() + 0 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 120,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 2,
    title: "Inglês",
    priorityLevel: 2,
    healthLevel: 1,
    expectedTimeHours: 150,
    needFocus: false,
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 240,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 3,
    title: "Ouvir Música",
    priorityLevel: 4,
    healthLevel: 3,
    expectedTimeHours: 60,
    workedTimeMinutes: 500,
    needFocus: true,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 4,
    title: "Jogar Futebol",
    priorityLevel: 1,
    healthLevel: 3,
    expectedTimeHours: 60,
    workedTimeMinutes: 426,
    needFocus: false,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 5,
    title: "Nadar",
    priorityLevel: 7,
    healthLevel: 3,
    expectedTimeHours: 60,
    needFocus: true,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 47747,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 6,
    title: "Programar",
    priorityLevel: 9,
    healthLevel: 3,
    expectedTimeHours: 60,
    needFocus: false,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 246642,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 7,
    title: "Adorar capivaras",
    priorityLevel: 1,
    healthLevel: 3,
    expectedTimeHours: 60,
    needFocus: true,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 42142,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 8,
    title: "Animes",
    priorityLevel: 1,
    healthLevel: 3,
    expectedTimeHours: 60,
    needFocus: false,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 444,
    createdAt: Date.now(),
    successful: false,
  },
  {
    id: 9,
    title: "Pudim",
    priorityLevel: 1,
    healthLevel: 1,
    expectedTimeHours: 60,
    needFocus: true,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).getTime(),
    workedTimeMinutes: 4244,
    createdAt: Date.now(),
    successful: false,
  },
] as TaskModel[];
